/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "JWTSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RecruitApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RecruitDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "RecruitVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}